# Generated by Django 2.2.3 on 2019-11-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparel_type', models.CharField(max_length=35)),
                ('size', models.CharField(blank=True, choices=[('large', 'L'), ('medium', 'M'), ('small', 'S'), ('extra_large', 'XL')], max_length=12, null=True)),
                ('cloth_type', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesOfClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='usedClothes/recycling_clothes')),
            ],
        ),
        migrations.CreateModel(
            name='RecycleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=8, unique=True)),
                ('sell_to', models.CharField(choices=[('us', "Sell to Us(Team Style'em.com)"), ('other_user', 'Put on Sale for anybody(Sell to any User)')], max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
                ('received', models.BooleanField(default=False)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usedClothes.Clothes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloth_related', to='usedClothes.ImagesOfClothes'),
        ),
    ]
