# Generated by Django 2.2.3 on 2019-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=264)),
                ('price', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/product_image/')),
                ('per_day_renting_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
            ],
        ),
    ]
